Fix compile errors for CLANG compiler
Use vector to fix "variable length array of non-POD element type" compiler error.
The /beignet/backend/src/./ir/context.hpp "fn->immediates[index] = imm" would call a private func
'operator=' which would trigger error, and it is not being used.
The undefined reference to `check_copy_overlap' would occur in the following calling.

Signed-off-by: Lv Meng <meng.lv@intel.com>
Reviewed-by: "Song, Ruiling" <ruiling.song@intel.com>